"""Initial schema

Revision ID: aea964c29646
Revises: 'None'
Create Date: 2026-07-22 20:02:23.356703

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aea964c29646'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_reports',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('candidate_id', sa.String(length=255), nullable=False),
    sa.Column('scenario_id', sa.String(length=255), nullable=False),
    sa.Column('overall_cognitive_index', sa.Float(), nullable=False),
    sa.Column('listening_metrics', sa.JSON(), nullable=False),
    sa.Column('speaking_metrics', sa.JSON(), nullable=False),
    sa.Column('construct_scores', sa.JSON(), nullable=False),
    sa.Column('evidence_summary', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_reports_candidate_id'), 'assessment_reports', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_assessment_reports_scenario_id'), 'assessment_reports', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_assessment_reports_session_id'), 'assessment_reports', ['session_id'], unique=False)
    op.create_table('assessment_scores',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('scenario_id', sa.String(length=255), nullable=False),
    sa.Column('construct_scores', sa.JSON(), nullable=False),
    sa.Column('composite_scores', sa.JSON(), nullable=False),
    sa.Column('reliability_summary', sa.JSON(), nullable=False),
    sa.Column('assessment_decision', sa.JSON(), nullable=False),
    sa.Column('scoring_metadata', sa.JSON(), nullable=False),
    sa.Column('pipeline_version', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_scores_scenario_id'), 'assessment_scores', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_assessment_scores_session_id'), 'assessment_scores', ['session_id'], unique=False)
    op.create_table('assessment_sessions',
    sa.Column('candidate_id', sa.String(length=255), nullable=False),
    sa.Column('scenario_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('completed_stages', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_sessions_candidate_id'), 'assessment_sessions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_assessment_sessions_scenario_id'), 'assessment_sessions', ['scenario_id'], unique=False)
    op.create_table('assessments',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('behavioral_evidences',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('prompt_id', sa.String(length=255), nullable=False),
    sa.Column('construct', sa.String(length=100), nullable=False),
    sa.Column('quote', sa.String(length=1000), nullable=False),
    sa.Column('indicator_description', sa.String(length=1000), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('polarity', sa.String(length=50), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavioral_evidences_construct'), 'behavioral_evidences', ['construct'], unique=False)
    op.create_index(op.f('ix_behavioral_evidences_session_id'), 'behavioral_evidences', ['session_id'], unique=False)
    op.create_table('construct_evaluations',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('construct_name', sa.String(length=100), nullable=False),
    sa.Column('construct_description', sa.String(length=500), nullable=False),
    sa.Column('behavioral_summary', sa.String(length=1000), nullable=False),
    sa.Column('supporting_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('evaluation_narrative', sa.String(length=4000), nullable=False),
    sa.Column('evaluation_confidence', sa.Float(), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_construct_evaluations_construct_name'), 'construct_evaluations', ['construct_name'], unique=False)
    op.create_index(op.f('ix_construct_evaluations_session_id'), 'construct_evaluations', ['session_id'], unique=False)
    op.create_table('platform_events',
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_events_correlation_id'), 'platform_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_platform_events_event_name'), 'platform_events', ['event_name'], unique=False)
    op.create_table('prompt_audits',
    sa.Column('prompt_id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('template_text', sa.String(length=4000), nullable=False),
    sa.Column('rendered_text', sa.String(length=4000), nullable=False),
    sa.Column('prompt_hash', sa.String(length=255), nullable=False),
    sa.Column('model_parameters', sa.JSON(), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_audits_prompt_id'), 'prompt_audits', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_prompt_audits_session_id'), 'prompt_audits', ['session_id'], unique=False)
    op.create_table('research_snapshots',
    sa.Column('research_metrics', sa.JSON(), nullable=False),
    sa.Column('analytics_metrics', sa.JSON(), nullable=False),
    sa.Column('validation_metrics', sa.JSON(), nullable=False),
    sa.Column('monitoring_metrics', sa.JSON(), nullable=False),
    sa.Column('experiment_results', sa.JSON(), nullable=False),
    sa.Column('platform_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('narrative', sa.String(length=4000), nullable=False),
    sa.Column('audio_asset', sa.JSON(), nullable=False),
    sa.Column('listening_questions', sa.JSON(), nullable=False),
    sa.Column('speaking_prompts', sa.JSON(), nullable=False),
    sa.Column('follow_up_definitions', sa.JSON(), nullable=False),
    sa.Column('construct_mappings', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcripts',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('prompt_id', sa.String(length=255), nullable=False),
    sa.Column('transcript_text', sa.String(length=4000), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_session_id'), 'transcripts', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_session_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_table('scenarios')
    op.drop_table('research_snapshots')
    op.drop_index(op.f('ix_prompt_audits_session_id'), table_name='prompt_audits')
    op.drop_index(op.f('ix_prompt_audits_prompt_id'), table_name='prompt_audits')
    op.drop_table('prompt_audits')
    op.drop_index(op.f('ix_platform_events_event_name'), table_name='platform_events')
    op.drop_index(op.f('ix_platform_events_correlation_id'), table_name='platform_events')
    op.drop_table('platform_events')
    op.drop_index(op.f('ix_construct_evaluations_session_id'), table_name='construct_evaluations')
    op.drop_index(op.f('ix_construct_evaluations_construct_name'), table_name='construct_evaluations')
    op.drop_table('construct_evaluations')
    op.drop_index(op.f('ix_behavioral_evidences_session_id'), table_name='behavioral_evidences')
    op.drop_index(op.f('ix_behavioral_evidences_construct'), table_name='behavioral_evidences')
    op.drop_table('behavioral_evidences')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_assessment_sessions_scenario_id'), table_name='assessment_sessions')
    op.drop_index(op.f('ix_assessment_sessions_candidate_id'), table_name='assessment_sessions')
    op.drop_table('assessment_sessions')
    op.drop_index(op.f('ix_assessment_scores_session_id'), table_name='assessment_scores')
    op.drop_index(op.f('ix_assessment_scores_scenario_id'), table_name='assessment_scores')
    op.drop_table('assessment_scores')
    op.drop_index(op.f('ix_assessment_reports_session_id'), table_name='assessment_reports')
    op.drop_index(op.f('ix_assessment_reports_scenario_id'), table_name='assessment_reports')
    op.drop_index(op.f('ix_assessment_reports_candidate_id'), table_name='assessment_reports')
    op.drop_table('assessment_reports')
    # ### end Alembic commands ###
