RESOURCES = {
    "AMBULANCE": "Ambulance",
    "FIRE_TRUCK": "Fire Truck",
    "POLICE": "Police Unit",
    "RESCUE": "Rescue Team",
}

ALL_SCENARIOS = [
    # Module 1: Baseline Assessment
    {
        "id": "m1_s1",
        "module": 1,
        "type": "Road Accident",
        "title": "Minor Intersection Collision",
        "description": "A two-vehicle collision at a major intersection. One driver is complaining of neck pain. Traffic is building up.",
        "location": "5th Ave & Main St",
        "severity": "Low",
        "livesAtRisk": 2,
        "priority": "low",
        "timeLimit": 25,
        "requiredResources": ["Ambulance", "Police Unit"],
    },
    {
        "id": "m1_s2",
        "module": 1,
        "type": "Medical Emergency",
        "title": "Elderly Collapse in Public Park",
        "description": "An elderly citizen has collapsed in a public park. Conscious but disoriented. Immediate medical response required.",
        "location": "Centennial Park",
        "severity": "Medium",
        "livesAtRisk": 1,
        "priority": "medium",
        "timeLimit": 20,
        "requiredResources": ["Ambulance"],
    },
    {
        "id": "m1_s3",
        "module": 1,
        "type": "Electrical Hazard",
        "title": "Sparking High-Voltage Transformer",
        "description": "A neighborhood transformer is sparking violently. A small crowd has gathered. High electrocution and fire hazard.",
        "location": "Elm Street Residential",
        "severity": "High",
        "livesAtRisk": 5,
        "priority": "high",
        "timeLimit": 20,
        "requiredResources": ["Fire Truck", "Police Unit"],
    },

    # Module 2: Stress Induction (Faster timers, complex multi-resource demands)
    {
        "id": "m2_s1",
        "module": 2,
        "type": "Building Fire",
        "title": "Apartment Complex Structural Fire",
        "description": "Flames spreading across 3rd floor. Residents trapped on balconies, dense toxic smoke filling the central stairwell.",
        "location": "Sunset Apartments",
        "severity": "Critical",
        "livesAtRisk": 14,
        "priority": "critical",
        "timeLimit": 12,
        "requiredResources": ["Fire Truck", "Ambulance", "Rescue Team"],
    },
    {
        "id": "m2_s2",
        "module": 2,
        "type": "Hazardous Gas Leak",
        "title": "Underground Gas Main Rupture",
        "description": "Intense methane odor detected near crowded shopping concourse. Explosive threshold imminent. Fast perimeter clearance required.",
        "location": "Downtown Metro Plaza",
        "severity": "Critical",
        "livesAtRisk": 25,
        "priority": "critical",
        "timeLimit": 12,
        "requiredResources": ["Police Unit", "Fire Truck"],
    },
    {
        "id": "m2_s3",
        "module": 2,
        "type": "Transit Pileup",
        "title": "Highway Multi-Vehicle Pileup",
        "description": "Heavy fog caused a chain-reaction crash involving an oil tanker and passenger cars. Multiple injured passengers pinned inside.",
        "location": "Highway 101 Northbound",
        "severity": "Critical",
        "livesAtRisk": 18,
        "priority": "critical",
        "timeLimit": 12,
        "requiredResources": ["Rescue Team", "Ambulance", "Fire Truck", "Police Unit"],
    },

    # Module 3: Failure & Recovery (High-stress failure events, tests resilience and error correction)
    {
        "id": "m3_s1",
        "module": 3,
        "type": "Structural Collapse",
        "title": "Parking Garage Floor Collapse",
        "description": "Second-story floor of a commercial parking garage gave way under construction load. Structural instability prevents safe entry.",
        "location": "Central Plaza Garage",
        "severity": "Critical",
        "livesAtRisk": 8,
        "priority": "critical",
        "timeLimit": 10,
        "requiredResources": ["Rescue Team", "Ambulance"],
    },
    {
        "id": "m3_s2",
        "module": 3,
        "type": "Industrial Chemical Spill",
        "title": "Chemical Plant Corrosive Leak",
        "description": "Industrial reactor valve failed. Acid vapor cloud migrating toward neighboring elementary school perimeter.",
        "location": "Industrial Zone Sector 4",
        "severity": "Critical",
        "livesAtRisk": 30,
        "priority": "critical",
        "timeLimit": 10,
        "requiredResources": ["Fire Truck", "Police Unit", "Rescue Team"],
    },
    {
        "id": "m3_s3",
        "module": 3,
        "type": "Subway Derailment",
        "title": "Subway Train Derailment in Tunnel",
        "description": "Underground express train derailed 500m inside tunnel. Total power loss, multiple crush injuries and panic reported.",
        "location": "Line 2 Metro Tunnel",
        "severity": "Critical",
        "livesAtRisk": 40,
        "priority": "critical",
        "timeLimit": 10,
        "requiredResources": ["Rescue Team", "Ambulance", "Fire Truck"],
    },

    # Module 4: Adaptive Challenge (Dynamic resource shortages and changing parameters)
    {
        "id": "m4_s1",
        "module": 4,
        "type": "Hospital Blackout",
        "title": "Major Hospital Backup Generator Failure",
        "description": "ICU life-support systems running on emergency batteries (under 10 minutes). Rapid evacuation and power triage required.",
        "location": "St. Jude General Hospital",
        "severity": "Critical",
        "livesAtRisk": 22,
        "priority": "critical",
        "timeLimit": 10,
        "requiredResources": ["Ambulance", "Fire Truck", "Police Unit"],
    },
    {
        "id": "m4_s2",
        "module": 4,
        "type": "Encroaching Wildfire",
        "title": "Rapid Brush Fire Threatening Suburb",
        "description": "Sudden wind shift pushed brush fire into residential canyon. Mandatory evacuation order issued for 50 homes.",
        "location": "Canyon Ridge Estates",
        "severity": "Critical",
        "livesAtRisk": 50,
        "priority": "critical",
        "timeLimit": 10,
        "requiredResources": ["Fire Truck", "Police Unit", "Rescue Team"],
    },
]
